# Generated by Django 4.2.30 on 2026-07-15 16:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否已审核')),
                ('apply_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请日期')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='审核日期')),
            ],
            options={
                'verbose_name': '论坛用户',
                'verbose_name_plural': '论坛用户',
                'ordering': ['-apply_date'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('views', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumuser', verbose_name='作者')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumuser', verbose_name='作者')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.topic', verbose_name='所属帖子')),
            ],
            options={
                'verbose_name': '回复',
                'verbose_name_plural': '回复',
                'ordering': ['created_at'],
            },
        ),
    ]
