# Generated by Django 4.2.30 on 2026-07-27 12:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('repo_url', models.CharField(max_length=500)),
                ('local_path', models.CharField(max_length=500)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='idle', max_length=50)),
                ('sync_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '笔记仓库',
                'verbose_name_plural': '笔记仓库',
            },
        ),
        migrations.CreateModel(
            name='NoteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=200)),
                ('extension', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True)),
                ('size', models.IntegerField(default=0)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('last_scanned', models.DateTimeField(default=django.utils.timezone.now)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.noterepository')),
            ],
            options={
                'verbose_name': '笔记文件',
                'verbose_name_plural': '笔记文件',
            },
        ),
    ]
