# Generated by Django 4.2.30 on 2026-07-27 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noterepository',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='noterepository',
            name='repo_type',
            field=models.CharField(choices=[('local', '本地仓库'), ('remote', '远程仓库')], default='remote', max_length=20),
        ),
        migrations.AlterField(
            model_name='noterepository',
            name='repo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
