# Generated by Django 4.2.30 on 2026-07-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_noterepository_created_at_noterepository_repo_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noterepository',
            name='branch',
            field=models.CharField(default='main', max_length=100),
        ),
    ]
