# Generated by Django 4.2.30 on 2026-07-14 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='工具名称')),
                ('description', models.TextField(verbose_name='工具描述')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('file', models.FileField(upload_to='tools/', verbose_name='工具文件')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('downloads', models.IntegerField(default=0, verbose_name='下载次数')),
            ],
            options={
                'verbose_name': '工具',
                'verbose_name_plural': '工具',
                'ordering': ['-upload_date'],
            },
        ),
    ]
