# Generated by Django 4.2.30 on 2026-07-18 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('airportal', 'AirPortal 空投'), ('wenshushu', '文叔叔')], max_length=20, verbose_name='平台')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='取件码')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='取件链接')),
                ('file_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='文件名')),
                ('file_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='文件大小')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '传输记录',
                'verbose_name_plural': '传输记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
